server:
  port: 8070
spring:
  jpa:
    defer-datasource-initialization: true
#    show-sql: true

  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: /api
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE